backend:
  name: test-repo
media_folder: static/img
public_folder: img
collections:
  - label: "Logos"
    name: "logos"
    files:
      - label: "Text Logos"
        name: "textLogos"
        file: "src/cms/logos/text.md"
        fields:
          - label: "Title"
            name: "title"
          - label: "Name"
            name: "name"
            widget: "object"
            fields:
              - label: "First text segment"
                name: "start"
              - label: "Second text segment (optional)"
                name: "end"
                required: "false"
          - label: "Font Family"
            name: "fontFamily"
